site_name: REDkit Open Documentation
site_url: https://redkit-resources.github.io/docs/
repo_name: redkit-resources/docs/
repo_url: https://github.com/redkit-resources/docs
edit_uri: edit/main/docs/
copyright: При поддержке сообщества REDkit RU

INHERIT: mkdocs.common.yml

nav:
  - Начало:
    - Добро пожаловать: index.md
    - Гайд для контрибьюторов: contribute.md
    - Журнал изменений: changelog.md
    - Благодарности: credits.md

  - Документация сообщества:
    - Главная: unnoficial_docs/index.md
    - Основы:
        Главная: unnoficial_docs/base/index.md
        Поведения:
          - Общие сведения: unnoficial_docs/base/behavior/behavior.md
        Мир:
          - Миры основы: unnoficial_docs/base/world/world.md

        Загрузочные экраны: unnoficial_docs/base/loading_screens.md

    - Гайды:
        - Главная: unnoficial_docs/guides/index.md
        - Создать анимацию для NPC: unnoficial_docs/guides/create_animation_for_npc.md
        - Создать USM видео: unnoficial_docs/guides/create_usm_video.md

    - Полезные фичи:
        - Главная: unnoficial_docs/useful_features/index.md
        - Полезные горячие клавиши: unnoficial_docs/useful_features/shortcuts.md
        - Cкопировать инфу из свойств объекта: unnoficial_docs/useful_features/copy_info_from_objects_prop.md
        - Настройка Script Studio: unnoficial_docs/useful_features/setup_script_studio.md

    - Баги и их решения:
        - Главная: unnoficial_docs/bugs/index.md
        - Швы на текстурах: unnoficial_docs/bugs/uv_bug.md

    - Справочники:
        - Главная: unnoficial_docs/references/index.md
        - Мир:
            - Параметры мира: unnoficial_docs/references/world/world_params.md
            - Umbra: unnoficial_docs/references/world/umbra.md
            - Параметры pathlib: unnoficial_docs/references/world/pathlib.md
            - Параметры теней: unnoficial_docs/references/world/shadow_params.md
            - Параметры окружения: unnoficial_docs/references/world/env_params.md
            - Параметры геометрии: unnoficial_docs/references/world/merged_geometry_params.md
        - Расширения файлов: unnoficial_docs/references/file_extensions.md
        - Типы данных параметров: unnoficial_docs/references/data_types.md